### ISSUE TITLE
GraalVm Visualizer interoperability with Java is broken

### ISSUE THREAD

**Issue by mbsl** [jmstoolbox/jmstoolbox#115]
## Specifications
- JMSToolBox version: 5.11.0
- OS (Name, version, 32/64bits): Wind10 64bit
- Q provider (kind, version) : Apache Artemis v2.x (but i think it doesnt really matter)

## Expected Behavior
The GraalVM integration in JMSToolbox can not handle interoperabilty with Java. 
Example script (basically taken from https://www.graalvm.org/reference-manual/js/#interoperability-with-java ), type INLINE_SCRIPT, Target JMS Message: TextMessage

```
var BigInteger = Java.type('java.math.BigInteger');
jtb_visualizer.showContent(".txt",BigInteger.valueOf(2).pow(100).toString(16));
```
The jtbVisualizer box should open and display the number 10000000000000000000000000

## Actual Behavior

An exception is displayed
```
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: ReferenceError: Java is not defined
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:381)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.access$400(GraalJSScriptEngine.java:77)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine$9.eval(GraalJSScriptEngine.java:533)
	at java.scripting/javax.script.CompiledScript.eval(Unknown Source)
	at org.titou10.jtb.visualizer.VisualizersManager.executeScript(VisualizersManager.java:445)
	at org.titou10.jtb.visualizer.VisualizersManager.launchVisualizer(VisualizersManager.java:377)
	at org.titou10.jtb.visualizer.ui.VisualizerShowPayloadAsHandler.execute(VisualizerShowPayloadAsHandler.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.ui.workbench.renderers.swt.DirectContributionItem.executeItem(DirectContributionItem.java:133)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
Caused by: org.graalvm.polyglot.PolyglotException: ReferenceError: Java is not defined
	at <js>.:program(<eval>:1)
	at org.graalvm.polyglot.Context.eval(Context.java:345)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:379)
	... 39 more
```

## Steps to Reproduce the Problem

  1. Have a TextMessage in a queue
  2. Create a visualizer script as mentioned before
  3. Try to open the message content with the visualizer

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by mbsl** [comment]
Maybe a solution is provided here: https://stackoverflow.com/questions/58995613/graalvm-polyglot-cant-load-java-class
