### ISSUE TITLE
JMSToolbox 5.5.0 and above does not work with OpenLiberty 22.0.0.13

### ISSUE THREAD

**Issue by roda69** [jmstoolbox/jmstoolbox#146]
## Specifications
- JMSToolBox version:5.5.0
- OS (Name, version, 32/64bits):Windows 10 64 bit and Linux 64 Bit
- Q provider (kind, version) : org.titou10.jtb.qm.liberty

## Expected Behavior
With JMSToolBox 5.4.0 I can connect and browse and administer queues

## Actual Behavior
same config with JMSToolBox 5.5.0 does not connect and I get this error

2023-02-06 12:08:40:755 DEBUG [o.t.j.j.m.JTBConnection     ] connect 'JTBConnection [jtbSessionClientType=GUI, isConnected()=false]'
2023-02-06 12:08:40:756 INFO  [o.t.j.q.l.LibertyQManager   ] connecting to localLiberty - JMSToolBox-1675685318649
2023-02-06 12:08:40:758 DEBUG [o.t.j.q.l.LibertyQManager   ] connecting to service:jmx:rest://localhost:9443/IBMJMXConnectorREST
2023-02-06 12:08:41:053 ERROR [o.t.j.u.JTBStatusReporter   ] Connect unsuccessful
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source) ~[na:na]
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source) ~[na:na]
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[na:na]
	at java.base/sun.security.validator.Validator.validate(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[na:na]
	at com.ibm.ws.jmx.connector.client.rest.internal.RESTMBeanServerConnection.loadJMXServerInfo(RESTMBeanServerConnection.java:243) ~[na:na]
	at com.ibm.ws.jmx.connector.client.rest.internal.RESTMBeanServerConnection.<init>(RESTMBeanServerConnection.java:160) ~[na:na]
	at com.ibm.ws.jmx.connector.client.rest.internal.Connector.connect(Connector.java:373) ~[na:na]
	at com.ibm.ws.jmx.connector.client.rest.internal.Connector.connect(Connector.java:116) ~[na:na]
	at org.titou10.jtb.qm.liberty.LibertyQManager.connect(LibertyQManager.java:165) ~[na:na]
	at org.titou10.jtb.jms.model.JTBConnection.connect(JTBConnection.java:267) ~[na:na]
	at org.titou10.jtb.handler.SessionConnectHandler$1.run(SessionConnectHandler.java:111) ~[na:na]
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72) ~[na:na]
	at org.titou10.jtb.handler.SessionConnectHandler.execute(SessionConnectHandler.java:106) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254) ~[na:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156) ~[na:na]
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497) ~[na:na]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:195) ~[na:na]
	at org.titou10.jtb.ui.part.JTBSessionsBrowserViewPart$1.doubleClick(JTBSessionsBrowserViewPart.java:159) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:833) ~[na:na]
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45) ~[na:na]
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47) ~[na:na]
	at org.eclipse.ui.internal.JFaceUtil$$Lambda$240.00000000163420A0.run(Unknown Source) ~[na:na]
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:830) ~[na:na]
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1518) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1260) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:253) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:251) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:310) ~[na:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89) ~[na:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131) ~[na:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055) ~[na:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944) ~[na:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661) ~[org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597) ~[org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476) ~[org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar:na]

## Steps to Reproduce the Problem

  1. Configure OpenLiberty with 1 or 2 queues, basic features and SSL
  2. download certificate from a browser and add to a local jks trustStore
  3. Configure JMSToolbox 5.5.0 or later to connect to the OpenLiberty (localhost)
  4. attempt to access the queue manager from JMSToolBox

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by roda69** [comment]
[](url)
[server.xml.txt](https://github.com/jmstoolbox/jmstoolbox/files/10663105/server.xml.txt)
[config.xml.txt](https://github.com/jmstoolbox/jmstoolbox/files/10663112/con
[jmstoolbox540.log](https://github.com/jmstoolbox/jmstoolbox/files/10663116/jmstoo
[jmstoolbox550.log](https://github.com/jmstoolbox/jmstoolbox/files/10663118/jmstoolbox550.log)
lbox540.log)
fig.xml.txt)

**Comment by roda69** [comment]
sorry accidentally closed this by mistake - uploaded logs

**Comment by titou10titou10** [comment]
My first impression is that it is due to the java 11.0.3 -> 11.0.4 upgrade between v5.4.0 and v5.5.0
Java v11.0.4 removed some CA, may be you are impacted

With v5.5.0, could you remove/rename the jre folder in the JMSToolBox folder and replace it with the jre folder from v5.4.0? or remove it and have your own java version on the path?
This will make v5.5.0 use  Java 11 v11.0.3 instead of v11.0.4
Also v5.5.0 is almost 3 years old... You should upgrade to the latest JTB version...

Java v11.0.4 release notes: https://www.oracle.com/java/technologies/javase/11-0-4-relnotes.html
Some other have similar problems that appeared with v11.0.4: https://www.eclipse.org/forums/index.php/t/1103235/

**Comment by roda69** [comment]
[jmstoolbox60_with_jre17.log](https://github.com/jmstoolbox/jmstoolbox/files/10664163/jmstoolbox60_with_jre17.log)

[jmstoolbox55_with_jre1103.log](https://github.com/jmstoolbox/jmstoolbox/files/10664165/jmstoolbox55_with_jre1103.log)

**Comment by roda69** [comment]
Thanks for responding so quickly. I first tried the latest which is version jmstoolbox-6.0.0-win32.win32.x86_64.zip then when it didnt work I tried several older versions until I found one which worked which was jmstoolbox-5.4.0-win32.win32.x86_64.zip. This is why I supplied logs from jmstoolbox-5.5.0-win32.win32.x86_64.zip originally as that one was the next version but didnt work. I have followed your suggestions and copied the older JRE from the working 5.4 into the 5.5 directory (C:\opt\JMSToolBox550) and it still did not work. 

I also supplied logs from version 6.0. I did add the -Djavax.net.debug=all to JMSToolBox.ini but it did not seem to add further logging. Did I add this in the wrong place?

`-startup
plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1000.v20190125-2016
-clean
-clearPersistedState
-data
@user.home/.jtb
-vmargs
-Xms512m
-Dorg.jboss.logging.provider=slf4j
-Djavax.net.debug=all`

**Comment by roda69** [comment]
your software is great by the way. If the worst comes to the worst I can use 5.4.0 but if there is anything I can do to help debug this (for me and others) I will be happy to try things. I could try another JDK (hotspot or a fresh Adoptium download or something)

**Comment by titou10titou10** [comment]
I thing this is a problem with the certificate you use but I don't know exactrly what it is. There is no code change in core JTB between v5.4.0 nd v5.5.0...
Your test with jre 17 is on Windows  10 and the other with Windows 8, I don't know if this makes a difference
In the preference, could you check 

    File > Preference > "Trust all server certificate..." and see if it works?
 
Also you wrote 

> 2. download certificate from a browser and add to a local jks trustStore

What do you mean? the truststore must contains the certificate used by JMX on the server, and the CA if you use a corporate CA non known to the  JRE

**Comment by roda69** [comment]
Hi, I just managed to get JMSToolbox 6.0 working by swapping in the latest Adoptium from OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10.msi and setting the path to its cacerts and importing my OpenLiberty cert into that.

My config now looks like this

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<config>
    <qManagerDef id="org.titou10.jtb.qm.liberty" name="IBM WebSphere Liberty">
        <jar>C:\opt\mw_lib\was90513\com.ibm.ws.ejb.thinclient_9.0.jar</jar>
        <jar>C:\opt\mw_lib\was90513\com.ibm.ws.orb_9.0.jar</jar>
        <jar>C:\opt\mw_lib\was90513\com.ibm.ws.sib.client.thin.jms_9.0.jar</jar>
        <jar>C:\opt\wlp\clients\restConnector.jar</jar>
    </qManagerDef>
    <sessionDef qManagerDef="org.titou10.jtb.qm.liberty" name="localLiberty">
        <host>localhost</host>
        <port>9443</port>
        <userid>admin</userid>
        <password>{##}CPrfsiZ1NANd/fbhxu+Prw==</password>
        <promptForCredentials>false</promptForCredentials>
        <properties>
            <property name="busName" value="defaultBus" kind="STRING"/>
            <property name="providerEndPoints" value="localhost:7276:BootstrapBasicMessaging" kind="STRING"/>
            <property name="targetTransportChain" value="InboundBasicMessaging" kind="STRING"/>
            <property name="javax.net.ssl.trustStore" value="C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot\lib\security\cacerts" kind="STRING"/>
            <property name="javax.net.ssl.trustStorePassword" value="{##}q6mA2hOR6tne4aaHvazo/Q==" kind="STRING"/>
            <property name="javax.net.ssl.trustStoreType" value="jks" kind="STRING"/>
        </properties>
    </sessionDef>
</config>
`

definite progress and I will test more tomorrow. I wonder if this is relevant?

https://www.eclipse.org/forums/index.php/t/1102068/

**Comment by roda69** [comment]
I will try generating my own signed certs as well tomorrow and wont rely on the automatically generated OpenLiberty one in case thats the issue.

**Comment by roda69** [comment]
File > Preference > "Trust all server certificate..." 

this worked as well with my original keystore (which only contained the auto-generated self-signed cert from OpenLiberty - exported from the browser) so thats another good workaround. Thank you very much for helping me with this. I will carry on testing later this week and provide feedback if I find anything else relevant.

**Comment by titou10titou10** [comment]
> Hi, I just managed to get JMSToolbox 6.0 working by swapping in the latest Adoptium from OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10.msi and setting the path to its cacerts and importing my OpenLiberty cert into that.

This tends to says that the CA of your certificate is not in your truststore but is in the cacert of the JDK . You need to identified the CA of your liberty certs and add it to your truststore

 
> I wonder if this is relevant? https://www.eclipse.org/forums/index.php/t/1102068/

Yes and no. eclipse IDE comes with an embedded JRE as a plugin. This is the equivalent of the `jre`directory under`JMSToolBox`

**Comment by roda69** [comment]
Hi,

I have done more testing and I think that when I run JMSToolBox.exe it is somehow ignoring the name and path to my custom keystore file and is instead using the default cacerts file. I did the following:-
1 - uninstalled all JDKs and JREs from windows 10
2 - rename C:\opt\JMSToolBox\jre\lib\security\cacerts to  C:\opt\JMSToolBox\jre\lib\security\cacerts.bak
3 - create a new empty JKS format kestore in the default path called  C:\opt\JMSToolBox\jre\lib\security\cacerts
4- import my root and intermediate CA into the new C:\opt\JMSToolBox\jre\lib\security\cacerts file
5 - create config enties to point to this new keystore in the default path beneath the JRE

```
            <property name="javax.net.ssl.trustStore" value="C:\opt\JMSToolBox\jre\lib\security\cacerts" kind="STRING"/>
            <property name="javax.net.ssl.trustStorePassword" value="{##}q6mA2hOR6tne4aaHvazo/Q==" kind="STRING"/>
            <property name="javax.net.ssl.trustStoreType" value="JKS" kind="STRING"/>
```

test and it connects sucessfully to my https OpenLiberty url

6 - rename the file C:\opt\JMSToolBox\jre\lib\security\cacerts to C:\opt\JMSToolBox\jre\lib\security\just_my_cacerts
7 - rename the original C:\opt\JMSToolBox\jre\lib\security\cacerts.bak back to C:\opt\JMSToolBox\jre\lib\security\cacerts
7 - update the config.xml (or via the UI) to point to the renamed just_my_cacerts file

```
            <property name="javax.net.ssl.trustStore" value="C:\opt\JMSToolBox\jre\lib\security\just_my_cacerts" kind="STRING"/>
            <property name="javax.net.ssl.trustStorePassword" value="{##}q6mA2hOR6tne4aaHvazo/Q==" kind="STRING"/>
            <property name="javax.net.ssl.trustStoreType" value="JKS" kind="STRING"/>
```

tested again and this time it fails, so it seems to work if the file is called cacerts in the default location but if the file has another name it does not work in spite of the config.xml pointing to the new name.

Please can you try this replication at your end with OpenLiberty sometime, to see if you experience a similar pattern where it seems to use the default cacerts file and not the custom file and path?

Thanks

Rod

**Comment by titou10titou10** [comment]
I was able to rerproduce the problem
 have a fix for it , it comes from this doc point 9: https://www.ibm.com/docs/en/was-liberty/core?topic=liberty-developing-jmx-java-client

> The Liberty REST connector allows a specific custom SSL socket factory to be used to obtain sockets. If the javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.j: PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target exception is displayed, you can create your own SSLContext from your own keystores and then use the SocketFactory from that context with the REST connector.

The fix will be included in the next version of JTB
