### ISSUE TITLE
IBM MQ can't connect to Websphere MQ ClassNotFoundException

### ISSUE THREAD

**Issue by pfeiler** [jmstoolbox/jmstoolbox#31]
## Specifications
- JMSToolBox version: v4.13.0
- OS (Name, version, 32/64bits): Windows 7 64bit
- Q provider (kind, version) : IBM MQ com.ibm.mq.allclient-9.0.4.0.jar (from https://mvnrepository.com/artifact/com.ibm.mq/com.ibm.mq.allclient/9.0.4.0)

## Expected Behavior
Connect to Websphere MQ 9.0.2.0

## Actual Behavior
![image](https://user-images.githubusercontent.com/15197136/46816003-56298300-cd7c-11e8-9795-a39317b42237.png)
Connect unsuccessful
Reason:
java.lang.ClassNotFoundException:  cannot found by org.titou10.jtb.qm.ibmmq_1.0.0.201809121543.jar 

## Steps to Reproduce the Problem

  1. Download com.ibm.mq.allclient-9.0.4.0.jar
  1. Download and start JMSToolBox
  2. Q Managers configure IBM MQ add com.ibm.mq.allclient-9.0.4.0.jar
  3. Create new session with IBM MQ and connection data and connect
  4. Error see above

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by pfeiler** [comment]
jmstoolbox.log :
`2018-10-11 17:39:59:623 INFO  [o.t.j.u.SLF4JConfigurator   ] Logging configuration initialised.
2018-10-11 17:39:59:630 DEBUG [o.t.j.c.JTBPreferenceStore  ] Loading Preference file 'C:\Users\lx671\.jtb\JMSToolBox\jmstoolbox.properties'
2018-10-11 17:39:59:736 DEBUG [o.t.j.c.ConfigManager       ] Parsing Configuration file 'config.xml'
2018-10-11 17:39:59:998 DEBUG [o.t.j.v.VariablesManager    ] Initializing VariablesManager
2018-10-11 17:40:00:021 DEBUG [o.t.j.v.VariablesManager    ] Parsing Variable file 'variables.xml'
2018-10-11 17:40:00:022 DEBUG [o.t.j.v.VariablesManager    ] VariablesManager initialized
2018-10-11 17:40:00:025 DEBUG [o.t.j.s.ScriptsManager      ] Initializing ScriptsManager
2018-10-11 17:40:00:059 DEBUG [o.t.j.s.ScriptsManager      ] Parsing Script file 'scripts.xml'
2018-10-11 17:40:00:060 DEBUG [o.t.j.s.ScriptsManager      ] ScriptsManager initialized
2018-10-11 17:40:00:067 DEBUG [o.t.j.v.VisualizersManager  ] Initializing VisualizersManager
2018-10-11 17:40:00:082 DEBUG [o.t.j.v.VisualizersManager  ] Parsing Visualizer file 'visualizers.xml'
2018-10-11 17:40:00:420 DEBUG [o.t.j.v.VisualizersManager  ] VisualizersManager initialized
2018-10-11 17:40:00:425 DEBUG [o.t.j.t.TemplatesManager    ] Initializing TemplatesManager
2018-10-11 17:40:00:450 DEBUG [o.t.j.t.TemplatesManager    ] Parsing Templates file 'templates.xml'
2018-10-11 17:40:00:452 DEBUG [o.t.j.t.TemplatesManager    ] TemplatesManager initialized
2018-10-11 17:40:00:457 DEBUG [o.t.j.c.ColumnsSetsManager  ] Initializing ColumnsSetsManager
2018-10-11 17:40:00:475 DEBUG [o.t.j.c.ColumnsSetsManager  ] Parsing ColumnsSets file 'columnssets.xml'
2018-10-11 17:40:00:484 DEBUG [o.t.j.c.ColumnsSetsManager  ] ColumnsSetsManager initialized
2018-10-11 17:40:00:487 DEBUG [o.t.j.s.SessionTypeManager  ] Initializing SessionTypeManager
2018-10-11 17:40:00:487 DEBUG [o.t.j.c.JTBPreferenceStore  ] getAllWithPrefix sessionttype.definition.
2018-10-11 17:40:00:491 DEBUG [o.t.j.s.SessionTypeManager  ] SessionTypeManager initialized
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.activemq'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.artemis'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.artemis2'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.hornetq'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.ibmmq'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.liberty'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.openmq'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.sonicmq'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.tibco'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.um'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.wassib'
2018-10-11 17:40:00:492 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.weblogic'
2018-10-11 17:40:00:493 DEBUG [o.t.j.c.ConfigManager       ] QM plugin found: 'org.titou10.jtb.qm.websphere'
2018-10-11 17:40:00:493 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.wassib'. No resource Bundle will be created for it.
2018-10-11 17:40:00:493 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.um'. No resource Bundle will be created for it.
2018-10-11 17:40:00:493 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.artemis2'. No resource Bundle will be created for it.
2018-10-11 17:40:00:493 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.openmq'. No resource Bundle will be created for it.
2018-10-11 17:40:00:494 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.hornetq'. No resource Bundle will be created for it.
2018-10-11 17:40:00:494 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.liberty'. No resource Bundle will be created for it.
2018-10-11 17:40:00:494 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.weblogic'. No resource Bundle will be created for it.
2018-10-11 17:40:00:494 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.activemq'. No resource Bundle will be created for it.
2018-10-11 17:40:00:494 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.sonicmq'. No resource Bundle will be created for it.
2018-10-11 17:40:00:494 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.tibco'. No resource Bundle will be created for it.
2018-10-11 17:40:00:495 DEBUG [o.t.j.u.JarUtils            ] pluginId 'org.titou10.jtb.qm.ibmmq': Creating a bundle with jars: 'external:F:/v/com.ibm.mq.allclient-9.0.4.0.jar'
2018-10-11 17:40:00:509 DEBUG [o.t.j.u.JarUtils            ] pluginId 'org.titou10.jtb.qm.ibmmq': Bundle created: C:/Users/lx671/.jtb/.metadata/.plugins/org.titou10.jtb.core/org.titou10.jtb.qm.ibmmq.resource.jar
2018-10-11 17:40:00:560 DEBUG [o.t.j.c.ConfigManager       ] State of resource bundle after start 32
2018-10-11 17:40:00:560 WARN  [o.t.j.c.ConfigManager       ] No 'QManagerDef' found in config file for pluginId 'org.titou10.jtb.qm.artemis'. No resource Bundle will be created for it.
2018-10-11 17:40:00:560 WARN  [o.t.j.u.JarUtils            ] pluginId 'org.titou10.jtb.qm.websphere': No jars found in 'QManagerDef' found in config file. No resource Bundle will be created for it.
2018-10-11 17:40:00:561 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.wassib' classname: 'org.titou10.jtb.qm.wassib.WASSIBQManager'
2018-10-11 17:40:00:564 DEBUG [o.t.j.q.w.WASSIBQManager    ] Instantiate LibertyQManager
2018-10-11 17:40:00:565 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'IBM WebSphere SIB'
2018-10-11 17:40:00:565 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.um' classname: 'org.titou10.jtb.qm.um.UMQManager'
2018-10-11 17:40:00:568 DEBUG [o.t.j.q.u.UMQManager        ] Instantiate UMQManager
2018-10-11 17:40:00:568 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'Software AG Universal Messaging'
2018-10-11 17:40:00:568 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.artemis2' classname: 'org.titou10.jtb.qm.artemis2.ActiveMQArtemis2QManager'
2018-10-11 17:40:00:585 DEBUG [o.j.logging                 ] Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2018-10-11 17:40:00:592 DEBUG [q.a.ActiveMQArtemis2QManager] Apache Active MQ Artemis v2.x+
2018-10-11 17:40:00:593 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'Apache Active MQ Artemis v2.x'
2018-10-11 17:40:00:593 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.openmq' classname: 'org.titou10.jtb.qm.openmq.OpenMQQManager'
2018-10-11 17:40:00:595 DEBUG [o.t.j.q.o.OpenMQQManager    ] Instantiate OpenMQ
2018-10-11 17:40:00:595 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'OpenMQ'
2018-10-11 17:40:00:595 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.hornetq' classname: 'org.titou10.jtb.qm.hornetq.HornetQQManager'
2018-10-11 17:40:00:598 DEBUG [o.t.j.q.h.HornetQQManager   ] Instantiate HornetQQManager
2018-10-11 17:40:00:598 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'HornetQ'
2018-10-11 17:40:00:598 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.liberty' classname: 'org.titou10.jtb.qm.liberty.LibertyQManager'
2018-10-11 17:40:00:600 DEBUG [o.t.j.q.l.LibertyQManager   ] Instantiate LibertyQManager
2018-10-11 17:40:00:600 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'IBM WebSphere Liberty'
2018-10-11 17:40:00:600 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.weblogic' classname: 'org.titou10.jtb.qm.weblogic.WebLogicQManager'
2018-10-11 17:40:00:603 DEBUG [o.t.j.q.w.WebLogicQManager  ] Instantiate WebLogicQManager
2018-10-11 17:40:00:603 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'Oracle WebLogic Server'
2018-10-11 17:40:00:604 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.activemq' classname: 'org.titou10.jtb.qm.activemq.ActiveMQQManager'
2018-10-11 17:40:00:611 DEBUG [o.t.j.q.a.ActiveMQQManager  ] Instantiate Apache Active MQ
2018-10-11 17:40:00:611 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'Apache Active MQ'
2018-10-11 17:40:00:611 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.sonicmq' classname: 'org.titou10.jtb.qm.sonicmq.SonicMQQManager'
2018-10-11 17:40:00:615 DEBUG [o.t.j.q.s.SonicMQQManager   ] Instantiate SonicMQQManager
2018-10-11 17:40:00:615 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'SonicMQ'
2018-10-11 17:40:00:615 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.tibco' classname: 'org.titou10.jtb.qm.tibco.TIBCOQManager'
2018-10-11 17:40:00:623 ERROR [o.t.j.c.ConfigManager       ] Problem when instatiating 'org.titou10.jtb.qm.tibco'. Skip it
org.eclipse.core.runtime.CoreException: Plug-in "org.titou10.jtb.qm.tibco" was unable to instantiate class "org.titou10.jtb.qm.tibco.TIBCOQManager".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:197) ~[org.eclipse.equinox.registry_3.8.0.v20180426-1327.jar:na]
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:191) ~[org.eclipse.equinox.registry_3.8.0.v20180426-1327.jar:na]
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:931) ~[org.eclipse.equinox.registry_3.8.0.v20180426-1327.jar:na]
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243) ~[org.eclipse.equinox.registry_3.8.0.v20180426-1327.jar:na]
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:60) ~[org.eclipse.equinox.registry_3.8.0.v20180426-1327.jar:na]
	at org.titou10.jtb.config.ConfigManager.instantiateQManagers(ConfigManager.java:641) [org.titou10.jtb.core_4.12.1.201809121543.jar:na]
	at org.titou10.jtb.config.ConfigManager.initConfig(ConfigManager.java:351) [org.titou10.jtb.core_4.12.1.201809121543.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55) [org.eclipse.e4.core.di_1.7.0.v20180427-1454.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318) [org.eclipse.e4.core.di_1.7.0.v20180427-1454.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:246) [org.eclipse.e4.core.di_1.7.0.v20180427-1454.jar:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:136) [org.eclipse.e4.core.contexts_1.7.0.v20180514-1409.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.lambda$0(E4Application.java:239) [org.eclipse.e4.ui.workbench.swt_0.14.200.v20180516-2019.jar:na]
	at java.util.Optional.ifPresent(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:235) [org.eclipse.e4.ui.workbench.swt_0.14.200.v20180516-2019.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:149) [org.eclipse.e4.ui.workbench.swt_0.14.200.v20180516-2019.jar:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) ~[org.eclipse.equinox.app_1.3.500.v20171221-2204.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656) ~[org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592) ~[org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498) ~[org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar:na]
Caused by: java.lang.NoClassDefFoundError: com/tibco/tibjms/admin/TibjmsAdminException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:1.8.0_181]
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[na:1.8.0_181]
	at java.lang.Class.getConstructor0(Unknown Source) ~[na:1.8.0_181]
	at java.lang.Class.newInstance(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:187) ~[org.eclipse.equinox.registry_3.8.0.v20180426-1327.jar:na]
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.tibco.tibjms.admin.TibjmsAdminException cannot be found by org.titou10.jtb.qm.tibco_1.0.0.201809121543
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_181]
	... 34 common frames omitted
2018-10-11 17:40:00:623 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.ibmmq' classname: 'org.titou10.jtb.qm.ibmmq.MQQManager'
2018-10-11 17:40:00:633 DEBUG [o.t.j.q.i.MQQManager        ] Instantiate MQQManager
2018-10-11 17:40:00:633 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'IBM MQ'
2018-10-11 17:40:00:633 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.artemis' classname: 'org.titou10.jtb.qm.artemis.ActiveMQArtemisQManager'
2018-10-11 17:40:01:094 DEBUG [.q.a.ActiveMQArtemisQManager] Apache Active MQ Artemis v1.x (legacy)
2018-10-11 17:40:01:095 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'Apache Active MQ Artemis'
2018-10-11 17:40:01:095 INFO  [o.t.j.c.ConfigManager       ] About to instantiate QM. id: 'org.titou10.jtb.qm.websphere' classname: 'org.titou10.jtb.qm.websphere.WASQManager'
2018-10-11 17:40:01:096 DEBUG [o.t.j.q.w.WASQManager       ] Instantiate WASQManager
2018-10-11 17:40:01:097 INFO  [o.t.j.c.ConfigManager       ] Instantiated Queue Manager 'IBM WebSphere'
2018-10-11 17:40:01:097 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.core_4.12.1.201809121543.jar
2018-10-11 17:40:01:097 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.activemq_1.0.0.201809121543.jar
2018-10-11 17:40:01:097 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.artemis_1.0.0.201809121543.jar
2018-10-11 17:40:01:097 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.artemis2_1.0.0.201809121543.jar
2018-10-11 17:40:01:097 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.hornetq_1.0.0.201809121543.jar
2018-10-11 17:40:01:097 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.ibmmq_1.0.0.201809121543.jar
2018-10-11 17:40:01:097 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.liberty_1.0.0.201809121543.jar
2018-10-11 17:40:01:097 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.openmq_1.0.0.201809121543.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.sonicmq_1.0.0.201809121543.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.tibco_1.0.0.201809121543.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.um_1.0.0.201809121543.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.wassib_1.0.0.201809121543.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.weblogic_1.0.0.201809121543.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.qm.websphere_1.0.0.201809121543.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : initial@reference:file:plugins/org.titou10.jtb.rest_1.0.0.201809121543.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] OSGI Bundle for JTBToolBox found : file:C:/Users/lx671/.jtb/.metadata/.plugins/org.titou10.jtb.core/org.titou10.jtb.qm.ibmmq.resource.jar
2018-10-11 17:40:01:098 DEBUG [o.t.j.c.ConfigManager       ] SessionDef found: rrh-msch-dev.dev.xyz.io
2018-10-11 17:40:01:099 DEBUG [o.t.j.c.ConfigManager       ] External Connector found: 'org.titou10.jtb.rest'
2018-10-11 17:40:01:119 DEBUG [o.t.j.r.RESTConnector       ] initialize: org.titou10.jtb.connector.ExternalConnectorManager@3f49e266
2018-10-11 17:40:01:209 INFO  [o.t.j.c.ConfigManager       ] External connector 'org.titou10.jtb.rest' initialized.
2018-10-11 17:40:01:210 DEBUG [o.t.j.c.ConfigManager       ] 
2018-10-11 17:40:01:210 INFO  [o.t.j.c.ConfigManager       ] ***************************************************
2018-10-11 17:40:01:210 INFO  [o.t.j.c.ConfigManager       ] * JMSToolBox v4.12.1 successfully initialized with:
2018-10-11 17:40:01:210 INFO  [o.t.j.c.ConfigManager       ] * -  13 installed plugins
2018-10-11 17:40:01:210 INFO  [o.t.j.c.ConfigManager       ] * -  12 running plugins
2018-10-11 17:40:01:210 INFO  [o.t.j.c.ConfigManager       ] * -   1 external connector plugins
2018-10-11 17:40:01:210 INFO  [o.t.j.c.ConfigManager       ] * -   2 QManagersDefs
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] * -   1 sessions
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] * -   0 scripts
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] * -   6 variables
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] * -   6 visualizers
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] * -   1 templates root folders
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] * -   1 columns sets
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] * -   3 session types
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] *
2018-10-11 17:40:01:211 INFO  [o.t.j.c.ConfigManager       ] * System Information:
2018-10-11 17:40:01:212 INFO  [o.t.j.c.ConfigManager       ] * - OS   : Name=Windows 7 Version=6.1 Arch=amd64
2018-10-11 17:40:01:213 INFO  [o.t.j.c.ConfigManager       ] * - Java : 1.8.0_181 (1.8.0_181-b13) Oracle Corporation 
2018-10-11 17:40:01:213 INFO  [o.t.j.c.ConfigManager       ] ***************************************************
2018-10-11 17:40:01:213 DEBUG [o.t.j.c.ConfigManager       ] 
2018-10-11 17:40:02:177 DEBUG [p.JTBSessionsBrowserViewPart] createControls
2018-10-11 17:40:02:178 DEBUG [p.JTBSessionsBrowserViewPart] buildSessionList
2018-10-11 17:40:03:165 DEBUG [o.t.j.c.MainWindowCloseAddon] register MainWindowCloseAddon Add On
2018-10-11 17:40:45:426 INFO  [u.p.QManagersBrowserViewPart] createControls
2018-10-11 17:40:46:919 DEBUG [j.h.QManagerConfigureHandler] execute
     2018-10-11 17:44:35:536 DEBUG [j.h.QManagerConfigureHandler] execute
2018-10-11 17:44:54:406 DEBUG [aultColumnsSetPropertyTester] showDefaultColumnsSet NodeJTBSession [rrh-msch-dev.dev.dbgcloud.io]
2018-10-11 17:44:55:530 DEBUG [o.t.j.h.SessionEditHandler  ] execute. Selection : NodeJTBSession [rrh-msch-dev.dev.dbgcloud.io]
2018-10-11 17:46:41:523 DEBUG [j.h.QManagerConfigureHandler] execute
2018-10-11 17:46:43:147 DEBUG [j.h.QManagerConfigureHandler] execute
`

**Comment by pfeiler** [comment]
Stacktrace:
`!STACK 0
java.lang.ClassNotFoundException:  cannot be found by org.titou10.jtb.qm.ibmmq_1.0.0.201809121543
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.titou10.jtb.qm.ibmmq.MQQManager.connect(MQQManager.java:279)
	at org.titou10.jtb.jms.model.JTBConnection.connect(JTBConnection.java:267)
	at org.titou10.jtb.handler.SessionConnectHandler$1.run(SessionConnectHandler.java:111)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:71)
	at org.titou10.jtb.handler.SessionConnectHandler.execute(SessionConnectHandler.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
`

**Comment by pfeiler** [comment]
Got it working, I can connect when I leave the Session Type empty. I had "Session Type = test" before, which leads to ClassNotFoundException.

**Comment by helmutat** [comment]
Hello,

i have the same issue (with latest version 5.4 as well as with 4.x) and also had session type with test before. Unfortunately, reset session type to empty didn't solve the problem. Also creating new session without having the session type did not help.

Any hint?

Thanks in advance!

**Comment by titou10titou10** [comment]
@helmutat, without more detail I can not help you................    
What jars did you defined in the MQ queue manager setup?    
could you send me the 2 logs files of JTB when the problem occur?    
What version of com.ibm.mq.allclient are you using and what is the version of MQ?    
On what OS are you running JMSToolBox?

**Comment by davsucks** [comment]
I had this same problem and was also able to resolve it by clearing the session type. Oddly enough after successfully connecting after clearing the session type I'm able to connect even after changing the session type back to 'Test'.

**Comment by titou10titou10** [comment]
@davsucks interesting. do you still have the JMSToolBox logs? could you send them to me? Thx

**Comment by davsucks** [comment]
@titou10titou10 sure thing! Just emailed them over to you at the email listed on your profile. Hope it helps!

**Comment by titou10titou10** [comment]
@helmutat and @pfeiler  what version of Java were you using with JMSToolBox when you add the probleme? Was it a version of Java different from Jaav 11? and on what OS?

@pfeiler, in the stacktrace you posted in your message, the class name is missing from the CNFE stacktrace. This is **very** strange !

    !STACK 0 java.lang.ClassNotFoundException: cannot be found by

**Comment by dangtuanhung** [comment]
@titou10titou10: I'm having the same problem, I've sent an email to you. Please check and help me to resolve this.

**Comment by titou10titou10** [comment]
@dangtuanhung did you follow the instructions to setup JTB to connect to IBM MQ?  https://github.com/jmstoolbox/jmstoolbox/wiki/2.1-Setup-for-IBM-MQ:, specially thi section: 

_If using v9.2+ version of the IBM MQ client jar, a JSON implementation jar must also be provided_

Did you provide such jar in addition to the  IBM MQ all client jar?

**Comment by titou10titou10** [comment]
@dangtuanhung I see in the log that you provided the following jars:

-  com.ibm.mq.allclient-9.2.5.0.jar
-  slf4j-api-1.5.2.jar
-  slf4j-simple-1.7.30.jar
-  tibcrypt.jar'

You must:
- remove all the jars except the com.ibm.mq.allclient-9.2.5.0.jar
- add a json implementation jar as specified in thw WiKi

**Comment by dangtuanhung** [comment]
Thank you so much.
I've lost that step, everything is ok now. Many thanks!

**Comment by weberjn** [comment]
Late to the party, for me it was ClassNotFoundException: org.json.JSONException
and solved by adding json-20160810.jar
