### ISSUE TITLE
Can't launch JMSToolBox on Linux

### ISSUE THREAD

**Issue by ElianWonhalf** [jmstoolbox/jmstoolbox#47]
## Specifications
- JMSToolBox version: 5.1.0
- OS (Name, version, 32/64bits): Linux Ubuntu 18.04 x64
- Q provider (kind, version) : N/A

## Expected Behavior
Launch JMSToolBox, the software window appears, I can interact with it.

## Actual Behavior
JMSToolBox displays the "Initializing" splashscreen, then closes with an error "An error has occured. See the log file [path]."

## Steps to Reproduce the Problem

  1. Download the archive from the releases
  2. Move it to /opt/ and run `tar zxvf [archive.tar.gz]`
  3. Go into the JMSToolBox folder and run `chmod +x JMSToolBox`
  4. Run `./JMSToolBox`

## Logs
```
!SESSION 2019-02-25 11:07:05.741 -----------------------------------------------
eclipse.buildId=unknown
java.version=10.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_CA
Framework arguments:  -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 -clean -clearPersistedState -data @user.home/.jtb

!ENTRY org.eclipse.equinox.app 0 0 2019-02-25 11:07:10.568
!MESSAGE Product org.titou10.jtb.core.product could not be found.

!ENTRY org.titou10.jtb.qm.wassib 2 0 2019-02-25 11:07:11.988
!MESSAGE Could not resolve module: org.titou10.jtb.qm.wassib [140]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.ibmmq 2 0 2019-02-25 11:07:11.989
!MESSAGE Could not resolve module: org.titou10.jtb.qm.ibmmq [134]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.artemis 2 0 2019-02-25 11:07:11.990
!MESSAGE Could not resolve module: org.titou10.jtb.qm.artemis [131]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.weblogic 2 0 2019-02-25 11:07:11.991
!MESSAGE Could not resolve module: org.titou10.jtb.qm.weblogic [141]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.activemq 2 0 2019-02-25 11:07:11.992
!MESSAGE Could not resolve module: org.titou10.jtb.qm.activemq [130]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.artemis2 2 0 2019-02-25 11:07:11.992
!MESSAGE Could not resolve module: org.titou10.jtb.qm.artemis2 [132]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.rest 2 0 2019-02-25 11:07:11.993
!MESSAGE Could not resolve module: org.titou10.jtb.rest [143]
  Unresolved requirement: Import-Package: org.titou10.jtb.connector
    -> Export-Package: org.titou10.jtb.connector; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.um 2 0 2019-02-25 11:07:11.994
!MESSAGE Could not resolve module: org.titou10.jtb.qm.um [139]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.core 2 0 2019-02-25 11:07:11.995
!MESSAGE Could not resolve module: org.titou10.jtb.core [129]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.openmq 2 0 2019-02-25 11:07:11.998
!MESSAGE Could not resolve module: org.titou10.jtb.qm.openmq [136]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.websphere 2 0 2019-02-25 11:07:12.001
!MESSAGE Could not resolve module: org.titou10.jtb.qm.websphere [142]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.liberty 2 0 2019-02-25 11:07:12.002
!MESSAGE Could not resolve module: org.titou10.jtb.qm.liberty [135]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.hornetq 2 0 2019-02-25 11:07:12.004
!MESSAGE Could not resolve module: org.titou10.jtb.qm.hornetq [133]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.sonicmq 2 0 2019-02-25 11:07:12.005
!MESSAGE Could not resolve module: org.titou10.jtb.qm.sonicmq [137]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.titou10.jtb.qm.tibco 2 0 2019-02-25 11:07:12.006
!MESSAGE Could not resolve module: org.titou10.jtb.qm.tibco [138]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.1.0.201902221323"; version="0.0.0"
       org.titou10.jtb.core [129]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.eclipse.osgi 4 0 2019-02-25 11:07:12.007
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
        at org.eclipse.emf.common.util.URI$URIPool$PlatformAccessUnit.setValue(URI.java:865)
        at org.eclipse.emf.common.util.URI$URIPool.intern(URI.java:1961)
        at org.eclipse.emf.common.util.URI.createPlatformPluginURI(URI.java:2750)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.determineApplicationModelURI(E4Application.java:415)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:356)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:153)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

**Comment by titou10titou10** [comment]
It seems you are using Java 10.0.2. Since v5.0.0, JMSToolBox requires Java 11: https://github.com/jmstoolbox/jmstoolbox/releases/tag/v5.0.0
You can find a free Java 11 Linux implementation here: [AdoptOpenJDK](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9#x64_linux)
Please upgrade your Java version and tell me how it goes

**Comment by ElianWonhalf** [comment]
Linux packages are weird, I installed something called "openjdk-11-jdk" and it's the version 10.

Thank you, it work with your link!
