### ISSUE TITLE
The application JMSToolbox 5.0.0 and 5.1.0 does not start on CentOS 6.10 

### ISSUE THREAD

**Issue by ruffp** [jmstoolbox/jmstoolbox#49]
## Specifications
- JMSToolBox version: 5.0.0 & 5.1.0
- OS (Name, version, 32/64bits): CentOS 6.10 64bits 
- Q provider (kind, version) : n/a

## Expected Behavior
The software should start

## Actual Behavior

When launching from command line ./JMSToolBox I got the message:

JMSToolBox:
An error has occurred. See the log file
/home/<USER>/.eclipse/1471219590_linux_gtk_x86_64/configuration/1551363844043.log.

and in the log I got:

```
!SESSION 2019-02-28 15:15:33.613 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 -clean -clearPersistedState -data @user.home/.jtb

!ENTRY org.eclipse.osgi 4 0 2019-02-28 15:15:38.690
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4922r32 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	no swt-pi4-gtk in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	Can't load library: /home/<USER>/.swt/lib/linux/x86_64/libswt-pi4-gtk-4922r32.so
	Can't load library: /home/<USER>/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:329)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:241)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:88)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:151)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

## Steps to Reproduce the Problem

1. OpenJDK installed under /usr/java/jdk-11.0.2 
2. Adapt the ini file to refer JDK path (see next section)
3. Launch the soft in command line

## Logs & Configs

My ini file:
```
-startup
plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.900.v20180922-1751
-clean
-clearPersistedState
-data
@user.home/.jtb
-vm
/usr/java/jdk-11.0.2/bin/java
-vmargs
-Xms512m
-Dorg.jboss.logging.provider=slf4j
```

My Linux is a VM under Windows 7 and will all latest updates installed. 

$ uname -a
Linux localhost.localdomain 2.6.32-754.10.1.el6.x86_64 #1 SMP Tue Jan 15 17:07:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I managed to install under Windows 7 (other package with embedded JRE) without any issues.

**Comment by titou10titou10** [comment]
Hi
Unfortunately this is a side effect of using the latest release of eclipse (eclipse v10: 2018-12) in JMSToolBox
Since this version of eclipse, GTK2 is no more supported: [Dropped support for GTK2](https://www.eclipse.org/eclipse/news/4.10/platform.php#gtk2-removal)
CentOS 6.x comes usually with GTK2 and I don't know if you can install GTK3
I will add this restriction on the JMSToolBox welcome page
I fear you'll have to stay with v4.14.0 (And java 8), or use another OS/version..
Denis
