### ISSUE TITLE
Failed to run 5.2.0 on Mac

### ISSUE THREAD

**Issue by tzoght** [jmstoolbox/jmstoolbox#54]
## Specifications
- JMSToolBox version: 5.2.0
- OS (Name, version, 32/64bits): OSX 10.14.4 (Mojave)
- Q provider (kind, version) : wasn't able to boot

## Expected Behavior
Running on MacOS

## Actual Behavior
Crashed with NPE

## Steps to Reproduce the Problem

  1. Download on to Mac, go to JMSToolBox.app/Content/MacOS
  1. chmod +x JMSToolBox
  1.run ./JMSToolBox

## Logs
ENTRY org.titou10.jtb.qm.hornetq 2 0 2019-04-25 19:33:21.137
!MESSAGE Could not resolve module: org.titou10.jtb.qm.hornetq [125]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.2.0.201904181752"; version="0.0.0"
       org.titou10.jtb.core [121]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

!ENTRY org.eclipse.osgi 4 0 2019-04-25 19:33:21.140
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
	at org.eclipse.emf.common.util.URI$URIPool$PlatformAccessUnit.setValue(URI.java:865)
	at org.eclipse.emf.common.util.URI$URIPool.intern(URI.java:1961)
	at org.eclipse.emf.common.util.URI.createPlatformPluginURI(URI.java:2750)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.determineApplicationModelURI(E4Application.java:415)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:356)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:153)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

**Comment by titou10titou10** [comment]
JMSToolBox 5+ requires Java 11

Based on the logs, It seems you are not using Java 11:

`Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"`
