### ISSUE TITLE
IBM MQ. JMSCC0005: The specified value is not allowed for 'XMSC_DESTINATION_NAME'. 

### ISSUE THREAD

**Issue by Renboo** [jmstoolbox/jmstoolbox#83]
## Specifications
- JMSToolBox version: 4.12.1 - latest
- OS (Name, version, 32/64bits): Windows Server 2016 Version=10.0 Arch=amd64

## Expected Behavior
Connection to MQ will be success.

## Actual Behavior
Received an errror:
JMSCC0005: The specified value '!!GHOST!416A9291!0!1CC8F369!220412' is not allowed for 'XMSC_DESTINATION_NAME'. 

## Steps to Reproduce the Problem

  1. Create ghost queue on IBM MQ. It usually has name like "!!GHOST!416A9291!0!1CC8F369!220412".
  2. Try to connect to it with JMSToolBox.

## Logs
2020-06-18 18:02:08:908 DEBUG [o.t.j.j.m.JTBConnection     ] connect 'JTBConnection [jtbSessionClientType=GUI, isConnected()=false]'
2020-06-18 18:02:08:909 INFO  [o.t.j.q.i.MQQManager        ] connecting to TEST-IBM-MQ - JMSToolBox-1592492516701
2020-06-18 18:02:10:106 INFO  [o.t.j.q.i.MQQManager        ] connected to TEST-IBM-MQ
2020-06-18 18:02:10:168 DEBUG [o.t.j.q.i.MQQManager        ] discoverDestinations : com.ibm.mq.jms.MQConnection@68631b1d - false
2020-06-18 18:02:10:198 DEBUG [o.t.j.q.i.MQQManager        ] Found Queue '!!GHOST!416A9291!0!1CC8F369!220413'. Type: LOCAL isBrowsable? true
2020-06-18 18:02:10:199 DEBUG [o.t.j.q.i.MQQManager        ] Found Queue '!!GHOST!416A9291!0!A086F818!6'. Type: LOCAL isBrowsable? true
2020-06-18 18:02:10:200 DEBUG [o.t.j.q.i.MQQManager        ] Found Queue 'AMQ.MQEXPLORER.5EC22EBE2A24BA16'. Type: LOCAL isBrowsable? true
2020-06-18 18:02:10:215 DEBUG [o.t.j.q.i.MQQManager        ] Found Queue 'SYSTEM.CLUSTER.HISTORY.QUEUE'. Type: LOCAL isBrowsable? true
2020-06-18 18:02:10:215 DEBUG [o.t.j.q.i.MQQManager        ] Found Queue 'SYSTEM.CLUSTER.REPOSITORY.QUEUE'. Type: LOCAL isBrowsable? true
2020-06-18 18:02:10:215 DEBUG [o.t.j.q.i.MQQManager        ] Found Queue 'SYSTEM.CLUSTER.TRANSMIT.MODEL.QUEUE'. Type: MODEL isBrowsable? false
2020-06-18 18:02:10:215 DEBUG [o.t.j.q.i.MQQManager        ] Found Queue 'SYSTEM.CLUSTER.TRANSMIT.QUEUE'. Type: LOCAL isBrowsable? true
2020-06-18 18:02:10:215 DEBUG [o.t.j.q.i.MQQManager        ] Found Queue 'SYSTEM.DDELAY.LOCAL.QUEUE'. Type: LOCAL isBrowsable? true
2020-06-18 18:02:10:233 DEBUG [o.t.j.q.i.MQQManager        ] Found Topic 'toUni'
2020-06-18 18:02:10:234 DEBUG [o.t.j.j.m.JTBConnection     ] jmsSession.createQueue '!!GHOST!416A9291!0!1CC8F369!220413'
2020-06-18 18:02:10:314 ERROR [o.t.j.u.JTBStatusReporter   ] Connect unsuccessful
com.ibm.msg.client.jms.DetailedJMSException: JMSCC0005: The specified value '!!GHOST!416A9291!0!1CC8F369!220412' is not allowed for 'XMSC_DESTINATION_NAME'.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_181]
	at com.ibm.msg.client.commonservices.j2se.NLSServices.createException(NLSServices.java:319) ~[na:na]
	at com.ibm.msg.client.commonservices.nls.NLSServices.createException(NLSServices.java:226) ~[na:na]
	at com.ibm.msg.client.jms.internal.JmsErrorUtils.createException(JmsErrorUtils.java:126) ~[na:na]
	at com.ibm.msg.client.jms.internal.JmsPropertyContextImpl.setObjectPropertyInternal(JmsPropertyContextImpl.java:452) ~[na:na]
	at com.ibm.msg.client.jms.internal.JmsPropertyContextImpl.setObjectProperty(JmsPropertyContextImpl.java:600) ~[na:na]
	at com.ibm.msg.client.wmq.common.internal.WMQPropertyContext.setObjectProperty(WMQPropertyContext.java:566) ~[na:na]
	at com.ibm.msg.client.wmq.common.internal.WMQPropertyContext.setStringProperty(WMQPropertyContext.java:621) ~[na:na]
	at com.ibm.msg.client.wmq.common.internal.WMQDestination.<init>(WMQDestination.java:3522) ~[na:na]
	at com.ibm.msg.client.wmq.common.internal.WMQDestination.<init>(WMQDestination.java:3478) ~[na:na]
	at com.ibm.msg.client.wmq.factories.WMQFactoryFactory.createProviderDestination(WMQFactoryFactory.java:271) ~[na:na]
	at com.ibm.msg.client.jms.admin.JmsDestinationImpl.setProviderDestination(JmsDestinationImpl.java:318) ~[na:na]
	at com.ibm.msg.client.jms.admin.JmsDestinationImpl.initialise(JmsDestinationImpl.java:216) ~[na:na]
	at com.ibm.msg.client.jms.admin.JmsDestinationImpl.<init>(JmsDestinationImpl.java:181) ~[na:na]
	at com.ibm.msg.client.jms.admin.JmsJndiDestinationImpl.<init>(JmsJndiDestinationImpl.java:124) ~[na:na]
	at com.ibm.mq.jms.MQDestination.<init>(MQDestination.java:199) ~[na:na]
	at com.ibm.mq.jms.MQQueue.<init>(MQQueue.java:134) ~[na:na]
	at com.ibm.msg.client.wmq.factories.admin.WMQJmsFactory.createQueue(WMQJmsFactory.java:163) ~[na:na]
	at com.ibm.msg.client.wmq.factories.admin.WMQJmsFactory.createQueue(WMQJmsFactory.java:465) ~[na:na]
	at com.ibm.msg.client.jms.internal.JmsSessionImpl.createQueue(JmsSessionImpl.java:1565) ~[na:na]
	at com.ibm.mq.jms.MQSession.createQueue(MQSession.java:682) ~[na:na]
	at org.titou10.jtb.jms.model.JTBConnection.connect(JTBConnection.java:280) ~[na:na]
	at org.titou10.jtb.handler.SessionConnectHandler$1.run(SessionConnectHandler.java:111) ~[na:na]
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:71) [org.eclipse.swt.win32.win32.x86_64_3.107.0.v20180611-0422.jar:na]
	at org.titou10.jtb.handler.SessionConnectHandler.execute(SessionConnectHandler.java:106) [org.titou10.jtb.core_4.12.1.201809121543.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55) [org.eclipse.e4.core.di_1.7.0.v20180427-1454.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318) [org.eclipse.e4.core.di_1.7.0.v20180427-1454.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252) [org.eclipse.e4.core.di_1.7.0.v20180427-1454.jar:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:161) [org.eclipse.e4.core.contexts_1.7.0.v20180514-1409.jar:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152) [org.eclipse.e4.core.commands_0.12.200.v20180427-0801.jar:na]
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494) [org.eclipse.core.commands_3.9.100.v20180404-1234.jar:na]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487) [org.eclipse.core.commands_3.9.100.v20180404-1234.jar:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204) [org.eclipse.e4.core.commands_0.12.200.v20180427-0801.jar:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:192) [org.eclipse.e4.core.commands_0.12.200.v20180427-0801.jar:na]
	at org.titou10.jtb.ui.part.JTBSessionsBrowserViewPart$1.doubleClick(JTBSessionsBrowserViewPart.java:159) [org.titou10.jtb.core_4.12.1.201809121543.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:830) [org.eclipse.jface_3.14.0.v20180423-0714.jar:na]
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) [org.eclipse.equinox.common_3.10.0.v20180412-1130.jar:na]
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44) [org.eclipse.ui.workbench_3.111.0.v20180524-1156.jar:na]
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173) ~[org.eclipse.jface_3.14.0.v20180423-0714.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:827) ~[org.eclipse.jface_3.14.0.v20180423-0714.jar:na]
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1512) ~[org.eclipse.jface_3.14.0.v20180423-0714.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1257) ~[org.eclipse.jface_3.14.0.v20180423-0714.jar:na]
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:249) ~[org.eclipse.jface_3.14.0.v20180423-0714.jar:na]
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:247) ~[org.eclipse.jface_3.14.0.v20180423-0714.jar:na]
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:306) ~[org.eclipse.jface_3.14.0.v20180423-0714.jar:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86) ~[org.eclipse.swt.win32.win32.x86_64_3.107.0.v20180611-0422.jar:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118) ~[org.eclipse.swt.win32.win32.x86_64_3.107.0.v20180611-0422.jar:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052) ~[org.eclipse.swt.win32.win32.x86_64_3.107.0.v20180611-0422.jar:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931) ~[org.eclipse.swt.win32.win32.x86_64_3.107.0.v20180611-0422.jar:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534) ~[org.eclipse.swt.win32.win32.x86_64_3.107.0.v20180611-0422.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170) ~[org.eclipse.e4.ui.workbench.swt_0.14.200.v20180516-2019.jar:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[org.eclipse.core.databinding.observable_1.6.200.v20180424-1922.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059) ~[org.eclipse.e4.ui.workbench.swt_0.14.200.v20180516-2019.jar:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153) ~[org.eclipse.e4.ui.workbench_1.6.0.v20180516-2019.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:162) ~[org.eclipse.e4.ui.workbench.swt_0.14.200.v20180516-2019.jar:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) ~[org.eclipse.equinox.app_1.3.500.v20171221-2204.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) ~[org.eclipse.osgi_3.13.0.v20180409-1500.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656) ~[org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592) ~[org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498) ~[org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar:na]

Decision:
Do not createQueue for names that contains chars like: !@;%, etc. It will be ok for all types of MQ.

Your code:
```
// Build lists of destinations
DestinationData dd = qm.discoverDestinations(jmsConnection, showSystemObjects);
for (QueueData qData : dd.getListQueueData()) {
	log.debug("jmsSession.createQueue '{}'", qData.getName());
	Queue jmsQ = jmsSession.createQueue(qData.getName());
	jtbQueues.add(new JTBQueue(this, qData.getName(), jmsQ, qData.isBrowsable()));
}
```
My offer:
```
DestinationData dd = qm.discoverDestinations(jmsConnection, showSystemObjects);
for (QueueData qData : dd.getListQueueData()) {
	if (!qData.getName().contains("!")) {
		log.debug("jmsSession.createQueue '{}'", qData.getName());
		Queue jmsQ = jmsSession.createQueue(qData.getName());
		jtbQueues.add(new JTBQueue(this, qData.getName(), jmsQ, qData.isBrowsable()));
	} else {
		log.debug("jmsSession.createQueue '{}' cound not be done for queue incorrect naming");
	}
}
```

**Comment by titou10titou10** [comment]
Thanks for reporting
Unfortunately, the JMS specs do not force naming convention on JMS destination names, it is left to the providers.

So it seems IBM MQ restrict some characters from being used in Q names, but it is not the case for other QM
I will add a filter for IBM MQ. 

BTW did you see [this bug?](https://www.ibm.com/support/pages/apar/IT11846)

**Comment by titou10titou10** [comment]
In fact it is not possible tocreate a queue with "!" in its name. When I try to create a Q with a "!" in its name, MQ Explorer reject it with 

    The name contains invalid characters. MQ object names can contain uppercase and lowercase letters, digits, and the characters './_%'

What I will do is exclude destinations with a name starting with`!!GHOST!` as it is used by specific internal feature of IBM MQ

**Comment by Renboo** [comment]
Thank you! I will be good solution too.

**Comment by Renboo** [comment]
I have tested it yesterday. Works perfect.
