### ISSUE TITLE
Trouble setting up the development environment

### ISSUE THREAD

**Issue by anqyan** [jmstoolbox/jmstoolbox#93]
## Specifications
- JMSToolBox version: On dev branch, commit 96fb64ce541b1367c32f76b32039aad6764c6cd7 (HEAD -> dev, origin/dev)
- OS (Name, version, 32/64bits): Windows 10 64bit
- Q provider (kind, version) : N/A

## Expected Behavior
I was following https://github.com/jmstoolbox/jmstoolbox/blob/dev/org.titou10.jtb.core/doc/setup_eclipse.txt
Couldn't get the below step working:
9. Run/test. Either:
  - open org.titou10.jtb.product/org.titou10.jtb.product, tab "overview", "Launch an eclipse application"

## Actual Behavior
Got Launch error:

![image](https://user-images.githubusercontent.com/55855049/97501402-6ba38280-192e-11eb-89f4-3d70831c5272.png)

## Steps to Reproduce the Problem
Followed https://github.com/jmstoolbox/jmstoolbox/blob/dev/org.titou10.jtb.core/doc/setup_eclipse.txt till step 9.

## Logs
Sample logs:
```
!SESSION 2020-10-28 14:59:17.433 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.8
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.titou10.jtb.core.product -clearPersistedState
Command-line arguments:  -product org.titou10.jtb.core.product -data C:\Users\ANQYAN\eclipse-workspace-2020/../runtime-org.titou10.jtb.product -dev file:C:/Users/ANQYAN/eclipse-workspace-2020/.metadata/.plugins/org.eclipse.pde.core/org.titou10.jtb.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -clean -clearPersistedState -data @user.home/.jtb

!ENTRY org.eclipse.ui.navigator 4 0 2020-10-28 14:59:18.621
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ui.navigator [28]
  Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.6.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.118.0.v20200807-0902"; singleton:="true"
       org.eclipse.ui [132]
         Unresolved requirement: Require-Bundle: org.eclipse.ui.workbench; bundle-version="[3.120.0,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.ui.workbench; bundle-version="3.120.0.v20200829-1411"; singleton:="true"
              org.eclipse.ui.workbench [121]
                Unresolved requirement: Import-Package: org.eclipse.e4.ui.internal.workbench.renderers.swt
                  -> Export-Package: org.eclipse.e4.ui.internal.workbench.renderers.swt; bundle-symbolic-name="org.eclipse.e4.ui.workbench.renderers.swt"; bundle-version="0.14.1300.v20200829-1411"; version="0.0.0"; x-friends:="org.eclipse.ui.workbench"
                     org.eclipse.e4.ui.workbench.renderers.swt [54]
                       Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.workbench.swt; bundle-version="0.9.0"
                         -> Bundle-SymbolicName: org.eclipse.e4.ui.workbench.swt; bundle-version="0.14.1100.v20200619-0644"; singleton:="true"
                            org.eclipse.e4.ui.workbench.swt [78]
                              Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.dialogs; bundle-version="1.1.600"
                Unresolved requirement: Import-Package: org.eclipse.e4.ui.internal.workbench.swt
                  -> Export-Package: org.eclipse.e4.ui.internal.workbench.swt; bundle-symbolic-name="org.eclipse.e4.ui.workbench.swt"; bundle-version="0.14.1100.v20200619-0644"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.workbench.addons.swt,org.eclipse.e4.ui.workbench.renderers.swt,org.eclipse.ui.workbench"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.titou10.jtb.qm.artemis2 2 0 2020-10-28 14:59:19.017
!MESSAGE Could not resolve module: org.titou10.jtb.qm.artemis2 [11]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.9.0.qualifier"; version="0.0.0"
       org.titou10.jtb.core [9]
         Unresolved requirement: Import-Package: org.slf4j

!ENTRY org.eclipse.e4.ui.workbench.swt 2 0 2020-10-28 14:59:19.018
!MESSAGE Could not resolve module: org.eclipse.e4.ui.workbench.swt [78]
  Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.dialogs; bundle-version="1.1.600"

!ENTRY org.titou10.jtb.qm.ibmmq 2 0 2020-10-28 14:59:19.019
!MESSAGE Could not resolve module: org.titou10.jtb.qm.ibmmq [14]
  Unresolved requirement: Import-Package: javax.jms
    -> Export-Package: javax.jms; bundle-symbolic-name="org.titou10.jtb.core"; bundle-version="5.9.0.qualifier"; version="0.0.0"
       org.titou10.jtb.core [9]
         Unresolved requirement: Import-Package: org.slf4j
```

Installed software:

![image](https://user-images.githubusercontent.com/55855049/97501809-2fbced00-192f-11eb-9306-fd33decc7ead.png)

**Comment by titou10titou10** [comment]
Thanks vfor reporting
There were a few missing dependent plugins in the product configuration. I also tried to be more precise in the docs
It should now work with the current dev branch (will be included in official 5.9.0 release)
